Fix fail to start
SyntaxError: invalid syntax

Regression introduced in 9dce565e1490c7f97e02220e3316f088d129a97c ("Unnecessary blank lines removed").

Reviewed-by: James Cameron <quozl@laptop.org>